version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
