version: '3.7'
services:
  mysql:
    image: postgres
    ports:
      - '3000:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=9mREsvXDs9Gk89Ef
